"""Synthetic operational monitoring: deterministic generator -> SQLite -> snapshot.

Uses Python 3.11+ standard library only. No company sources or external calls.
"""
from pathlib import Path
from datetime import date, timedelta
import csv
import json
import random
import sqlite3

ROOT = Path(__file__).resolve().parent
REGIONS = ('North', 'South', 'East')
STAMP = '2026-10-01T00:00:00Z'


def generate(seed=26):
    rng = random.Random(seed)
    rows = []
    for offset in range(90):
        day = date(2026, 7, 3) + timedelta(days=offset)
        for i in range(120):
            region = REGIONS[i % 3]
            provider = 'Alpha' if i % 2 else 'Beta'
            received = 96 - rng.randrange(0, 7)
            # Inject a labelled synthetic outage; this is not a causal estimate.
            if 70 <= offset <= 74 and region == 'South' and provider == 'Beta':
                received = rng.randrange(38, 60)
            invalid = rng.choice((0, 0, 0, 1, 2, 4))
            incident = int(received < 0.9 * 96 or invalid / max(received, 1) > 0.02)
            rows.append(dict(day=day.isoformat(), asset_id=f'ASSET-{i+1:04}',
                             region=region, provider=provider, expected=96,
                             received=received, invalid=invalid, incident=incident))
    return rows


def database(rows):
    con = sqlite3.connect(':memory:')
    con.row_factory = sqlite3.Row
    con.execute('''CREATE TABLE readings (
        day TEXT NOT NULL, asset_id TEXT NOT NULL, region TEXT NOT NULL,
        provider TEXT NOT NULL, expected INTEGER CHECK(expected>0),
        received INTEGER CHECK(received BETWEEN 0 AND expected),
        invalid INTEGER CHECK(invalid BETWEEN 0 AND received),
        incident INTEGER CHECK(incident IN (0,1)), PRIMARY KEY(day,asset_id))''')
    con.executemany('INSERT INTO readings VALUES (:day,:asset_id,:region,:provider,:expected,:received,:invalid,:incident)', rows)
    con.executescript((ROOT/'sql/metrics.sql').read_text())
    return con


def extract(con):
    def query(sql):
        return [dict(r) for r in con.execute(sql)]
    overview = query('SELECT * FROM recent_metrics ORDER BY region')
    total = query('''SELECT 'All' region, COUNT(DISTINCT asset_id) assets,
        SUM(expected) expected, SUM(received) received, SUM(invalid) invalid,
        SUM(incident) incident_days, 1.0*SUM(received)/SUM(expected) completeness,
        CASE WHEN SUM(received)=0 THEN NULL ELSE
        1.0*(SUM(received)-SUM(invalid))/SUM(received) END validity
        FROM readings WHERE day BETWEEN '2026-09-24' AND '2026-09-30' ''')
    trend = query('SELECT * FROM daily_metrics ORDER BY day,region')
    trend += query('''SELECT day,'All' region,SUM(expected) expected,
        SUM(received) received,SUM(invalid) invalid,SUM(incident) incidents,
        1.0*SUM(received)/SUM(expected) completeness,
        1.0*(SUM(received)-SUM(invalid))/NULLIF(SUM(received),0) validity
        FROM readings GROUP BY day ORDER BY day''')
    providers = query('SELECT * FROM provider_metrics ORDER BY region,provider')
    providers += query('''SELECT 'All' region,provider,SUM(expected) expected,
        SUM(received) received,1.0*SUM(received)/SUM(expected) completeness
        FROM readings WHERE day BETWEEN '2026-09-24' AND '2026-09-30'
        GROUP BY provider ORDER BY provider''')
    incidents = query('''SELECT day,asset_id,region,provider,expected,received,invalid
        FROM readings WHERE incident=1 AND day BETWEEN '2026-09-24' AND '2026-09-30'
        ORDER BY day DESC,asset_id''')
    # Explicit All is a real aggregate; percentages never averaged across regions.
    incidents += [dict(r, region='All', asset_region=r['region']) for r in incidents]
    return dict(overview=total+overview, trend=trend, providers=providers, incidents=incidents)


def artifact(data):
    source = dict(id='synthetic_sql', label='Synthetic operations · SQLite metrics',
                  path='sql/metrics.sql', query=dict(engine='SQLite', language='sql',
                  sql=(ROOT/'sql/metrics.sql').read_text(),
                  description='Deterministic fictional asset-day readings generated by pipeline.py, seed 26. All aggregations use sums of numerators and denominators.',
                  tables_used=['readings'], executed_at=STAMP,
                  filters=['Overview and provider comparison: 24–30 September 2026 inclusive.',
                           'Trend: 3 July–30 September 2026 inclusive.'],
                  metric_definitions={'completeness':'Received intervals / expected intervals; 96 expected per asset-day.',
                  'validity':'(Received - invalid intervals) / received intervals; NULL if no intervals received.',
                  'incident_days':'Asset-days with <90% completeness or >2% invalid intervals; rule-based review flag, not a failure diagnosis.'}))
    cards=[]
    for field,label,fmt,desc in [
        ('assets','Monitored assets','number','Distinct assets in the selected region, 24–30 Sep 2026.'),
        ('completeness','Reading completeness','percent','Received / expected intervals, 24–30 Sep 2026.'),
        ('validity','Valid received intervals','percent','Valid / received intervals, 24–30 Sep 2026.'),
        ('incident_days','Flagged asset-days','number','Review flags: <90% completeness or >2% invalid intervals, 24–30 Sep 2026.')]:
        cards.append(dict(id=field, dataset='overview', sourceId=source['id'],
                          description=desc,metrics=[dict(field=field,label=label,format=fmt)]))
    manifest=dict(version=1,surface='dashboard',title='Operations Analytics Dashboard',
        description='Synthetic portfolio demo · Python + SQL · 120 fictional assets · 90 days',generatedAt=STAMP,
        filters=[dict(id='region',label='Region',dataset='overview',field='region',
            defaultValue='All',includeAll=False,targets=[dict(dataset=d,field='region') for d in ('trend','providers','incidents')])],
        cards=cards,charts=[
            dict(id='coverage',title='Daily reading completeness',type='line',dataset='trend',sourceId=source['id'],
                 encodings=dict(x=dict(field='day',type='temporal',label='Day'),
                                y=dict(field='completeness',type='quantitative',label='Completeness',format='percent')),valueFormat='percent'),
            dict(id='providers',title='Reading completeness by provider',type='bar',dataset='providers',sourceId=source['id'],
                 encodings=dict(x=dict(field='provider',type='nominal',label='Provider'),
                                y=dict(field='completeness',type='quantitative',label='Completeness',format='percent')),valueFormat='percent')],
        tables=[dict(id='exceptions',title='Operational review queue · 24–30 Sep',dataset='incidents',sourceId=source['id'],
                     defaultSort=dict(field='day',direction='desc'),columns=[
                         dict(field=f,label=l,type=t) for f,l,t in [('day','Day','text'),('asset_id','Asset','text'),
                         ('provider','Provider','text'),('received','Received intervals','number'),('invalid','Invalid intervals','number')]])],
        sources=[source],blocks=[
            dict(id='intro',type='markdown',body='# Operations Analytics Dashboard\n\nSynthetic portfolio demo. Last complete day: **30 Sep 2026**. KPI cards cover **24–30 Sep**; the trend covers 90 days. Select a region to investigate coverage and data quality.'),
            dict(id='kpis',type='metric-strip',cardIds=[c['id'] for c in cards]),
            dict(id='trend',type='chart',chartId='coverage'),dict(id='provider',type='chart',chartId='providers'),
            dict(id='queue',type='table',tableId='exceptions'),
            dict(id='definitions',type='markdown',sourceId=source['id'],body='## Definitions and limits\n\n**Completeness:** received ÷ expected intervals (96 per asset-day). **Validity:** valid ÷ received intervals. **Flags:** asset-days below 90% completeness or above 2% invalid intervals. Flags require investigation; they do not diagnose equipment failures. The same rule is applied to every provider.\n\nAll assets, providers and readings are fictional. The South/Beta outage is deliberately injected. This is a fixed snapshot, with no live connection or refresh. Python regenerates data and snapshot JSON; this HTML is the reviewed presentation.')])
    return dict(surface='dashboard',manifest=manifest,snapshot=dict(version=1,status='fixture',generatedAt=STAMP,datasets=data),sources=[source])


def main():
    import argparse
    import subprocess
    from export_snapshot import verify
    parser=argparse.ArgumentParser(description='Generate synthetic data and verify the published presentation.')
    parser.add_argument('--renderer',type=Path,help='Path to the canonical deliver_portable_artifact.mjs exporter; needed when presentation data changes.')
    args=parser.parse_args()
    rows=generate()
    out=ROOT/'outputs'; out.mkdir(exist_ok=True)
    with (out/'synthetic_readings.csv').open('w',newline='') as f:
        writer=csv.DictWriter(f,fieldnames=list(rows[0]));writer.writeheader();writer.writerows(rows)
    con=database(rows)
    with sqlite3.connect(out/'operations.sqlite') as disk:
        con.backup(disk)
    data=extract(con)
    (out/'snapshot.json').write_text(json.dumps(data,indent=2))
    (ROOT/'artifact.json').write_text(json.dumps(artifact(data),indent=2))
    if args.renderer:
        subprocess.run(['node',str(args.renderer),'--input',str(ROOT/'artifact.json'),
            '--output',str(ROOT/'index.html')],check=True)
    verify()
    print(f'Generated {len(rows):,} fictional asset-days. Fixed seed: 26. Last data day: 2026-09-30.')
    print(json.dumps(data['overview'][0],indent=2))
    print('HTML matches the generated snapshot. Open index.html; outputs contain CSV, SQLite and JSON.')
    con.close()


if __name__=='__main__':
    main()
